# Generated by Django 5.0.2 on 2024-02-23 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Livros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("autor", models.CharField(max_length=30)),
                ("co_autor", models.CharField(max_length=30)),
                ("data_registo", models.DateField(default=datetime.date.today)),
                ("emprestado", models.BooleanField(default=False)),
                (
                    "nome_emprestado",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("data_emprestimo", models.DateTimeField(blank=True, null=True)),
                ("data_devolucao", models.DateTimeField(blank=True, null=True)),
                ("tempo_duracao", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Livro",
            },
        ),
    ]
