# Generated by Django 5.0.2 on 2024-02-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livros",
            name="nome_emprestado",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
